version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-call-center
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - call-center-network

volumes:
  redis-data:

networks:
  call-center-network:
    driver: bridge
